### ISSUE TITLE
Create skeuomorphism Login UI 

### ISSUE THREAD

**Issue by Roshaen** [Clueless-Community/flutter-ui-components#9] opened 2022-10-08 18:44 UTC
Implement a Login UI which follows skeuomorphism design system
Refer google for skeuomorphism

**Comment by Aaliya-Ali** [comment] 2022-10-12 04:55
Hello,
I see that the issue is still open. If so, I'd like to work on it.

**Comment by Roshaen** [comment] 2022-10-12 06:20
Sure Go ahead

**Comment by sowmiya-venkatesan** [comment] 2022-10-16 08:24
Hi @Roshaen , I would like to contribute to this issue, much appreciated, if you can assign me this issue!

**Comment by Roshaen** [comment] 2022-10-16 08:34
Sure @sowmiya-venkatesan 
Assigning to you
Follow the contribution guidelines for proper folder structure

**Comment by Tushar98644** [comment] 2022-12-06 18:19
pls assign this to me...

**Comment by Roshaen** [comment] 2022-12-07 07:04
Sure @Tushar98644

**Comment by Tushar98644** [comment] 2022-12-07 17:31
kindly review the pr @Roshaen

**Closed** 2023-02-06 14:24 UTC
Labels: UI, MEDIUM, CodePeak’22
